version: '3.8'

services:  

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - observe-network
    env_file: .env
    volumes:
        - ./prometheus/prometheus.yml.template:/etc/prometheus/prometheus.yml.template
    entrypoint: /bin/sh
    command: 
      - -c
      - |
        sed -e 's/$$CONSUL_HOST/${CONSUL_HOST}/g' -e 's/$$CONSUL_PORT/${CONSUL_PORT}/g' /etc/prometheus/prometheus.yml.template > /tmp/prometheus.yml && \
        cat /tmp/prometheus.yml && \
        exec /bin/prometheus --config.file=/tmp/prometheus.yml --web.enable-lifecycle
    environment:
      - CONSUL_HOST=${CONSUL_HOST}
      - CONSUL_PORT=${CONSUL_PORT}
    
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - observe-network
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Change in production!
      - GF_USERS_ALLOW_SIGN_UP=false

# Define networks and volumes
networks:
  observe-network:
    driver: bridge

volumes:
  pgdata:
  grafana-storage:
